services:
  - type: web
    name: expoai-crm
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: python manage.py migrate && gunicorn config.wsgi
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
