# Generated by Django 5.2.12 on 2026-03-07 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('organizer', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-start_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id_code', models.CharField(blank=True, max_length=50)),
                ('fair_id_code', models.CharField(blank=True, max_length=50)),
                ('company_name', models.CharField(max_length=255)),
                ('authorized_person', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('company_status', models.CharField(blank=True, choices=[('katiliyor', 'Katılıyor'), ('katilmiyor', 'Katılmıyor'), ('ulasilamadi', 'Ulaşılamadı'), ('tekrar_ara', 'Tekrar Ara'), ('iptal', 'İptal'), ('teklif_ver', 'Teklif Ver'), ('sozlesme_hazirla', 'Sözleşme Hazırla')], max_length=50)),
                ('next_action', models.CharField(blank=True, choices=[('ara', 'Ara'), ('mail_at', 'Mail At'), ('teklif_hazirla', 'Teklif Hazırla'), ('toplanti_yap', 'Toplantı Yap'), ('takip_et', 'Takip Et')], max_length=50)),
                ('last_contact', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to=settings.AUTH_USER_MODEL)),
                ('fair', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='crm.fair')),
            ],
            options={
                'ordering': ['company_name'],
            },
        ),
    ]
